app/Ecommerce/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls.static import static
from . import settings
from .views import home
import produtos.urls
import categorias.urls
import accounts.urls
import carrinho.urls
import pedidos.urls

urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('allauth.socialaccount.providers.google.urls')),
    path('accounts/', include('allauth.socialaccount.providers.twitter.urls')),
    path('accounts/', include('allauth.urls'), name='socialaccount_signup'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('users/', include(accounts.urls, namespace='users')),
    path('produtos/', include(produtos.urls)),
    path('categorias/', include(categorias.urls)),
    path('carrinho/', include(carrinho.urls)),
    path('pedidos/', include(pedidos.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/urls.py
from django.urls import path
from accounts.views import addEndereco, cadastra_user, retorna_account, remover_endereco, retorna_perfil

app_name = 'account'

"""
Urls do app account.
"""

urlpatterns = [
    path('<int:pk>/', retorna_account, name='retrieve'),
    path('cadastrar/', cadastra_user, name='cadastrar'),
    path('cadastrar_endereco/', addEndereco, name='cadastrar_endereco'),
    path('remover_endereco/<int:pk>/', remover_endereco, name='remover_endereco'),
    path('perfil/', retorna_perfil, name='retorna_perfil')
]

app/carrinho/urls.py
from django.urls import path
from carrinho.views import retorna_carrinho, adicionar, remover

app_name = 'carrinho'

"""
URLs do app carrinho.
"""

urlpatterns = [
    path('', retorna_carrinho, name='retrieve'),
    path('adicionar/<int:pk>/', adicionar, name='adicionar'),
    path('remover/<int:pk>/', remover, name='remover')
]

app/categorias/urls.py
from django.urls import path
from categorias.views import retorna_produtos_categoria

app_name = 'categorias'

"""
Urls do app categorias.
"""

urlpatterns = [
    path('<int:pk>/produtos/', retorna_produtos_categoria, name='list'),
]

app/pedidos/urls.py
from django.urls import path
from pedidos.views import identificacao, pagamento, session_cart_to_account_cart, inicia_pedido, continua_pedido, finaliza_pedido, confirmacao_pedido
from accounts.views import retorna_enderecos

app_name = 'pedidos'

"""
Urls do app pedidos.
"""

urlpatterns = [
    path('identificacao/', identificacao, name='identificacao'),
    path('endereco/', retorna_enderecos, name='endereco'),
    path('pagamento/', pagamento, name='pagamento'),
    path('session-to-account/', session_cart_to_account_cart, name='session-to-account'),
    path('inicia-pedido/', inicia_pedido, name='inicia-pedido'),
    path('continua-pedido/', continua_pedido, name='continua-pedido'),
    path('finaliza-pedido/<int:fm>/', finaliza_pedido, name='finaliza-pedido'),
    path('confirmacao/', confirmacao_pedido, name='confirmacao')
]

app/produtos/urls.py
from produtos.views import retorna_produtos, retorna_produtos_mais_recentes, retorna_produtos_mais_vendidos, retorna_produtos_mais_visualizados, detalhes_produto
from django.urls import path

app_name = 'produtos'

"""
URLs do app produtos.
"""

urlpatterns = [
    path('<int:pk>/', detalhes_produto, name='detalhes_produto'),
    path('list/', retorna_produtos, name='list'),
    path('maisVendidos/', retorna_produtos_mais_vendidos, name='maisVendidos'),
    path('maisVistos/', retorna_produtos_mais_visualizados, name='maisVistos'),
    path('lancamentos/', retorna_produtos_mais_recentes, name='lancamentos'),
]

app/templates/snippets/carrossel.html
{% load static %}

{% block carrossel %}  

<link rel="stylesheet" href="{% static 'css/style-carrossel.css' %}">

<p id="aaa">Nossas categorias</p>

<article id="carrossel-container" class="c-carousel c-carousel--responsive">
    <div class="c-carousel__slides js-carousel--responsive">
        {% for categoria in categorias %}

        <article class="cards">
            <a href="{% url 'categorias:list' pk=categoria.id %}">
            <img src="{{categoria.imagem.url}}" alt="Foto de {{categoria.nome}}">
            <p><strong>{{categoria.nome}}</strong></p>
            </a>
        </article>

        {% endfor %}
    </div>
    <div class="buttons">
        <a id="button-prev" class="js-carousel--responsive-prev" aria-label="Anterior"><i class="fas fa-chevron-circle-left"></i></a>
        <a id="button-next" class="js-carousel--responsive-next" aria-label="Próximo"><i class="fas fa-chevron-circle-right"></i></a>
    </div>
    <div id="dots" class="js-carousel--responsive-dots" role="tablist"></div>
</article>

<script src="{% static 'js/carrossel.js' %}"></script>
    
{% endblock %}

app/templates/snippets/footer-home.html
{% load static %}

{% block footer %}

<link rel="stylesheet" href="{% static 'css/style-footer-home.css' %}">

    <h3>SySales</h3>
    <p>O lugar perfeito para o seu E-commerce</p>
    <ul class="socials">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-youtube"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
    </ul>
    <div class="footer-bottom">
        <p>copyright &copy;2021 SySales.</p>
    </div>


{% endblock %}

app/templates/snippets/footer.html
{% load static %}

{% block footer %}

<link rel="stylesheet" href="{% static 'css/style-footer.css' %}">

    <h3>SySales</h3>
    <p>O lugar perfeito para o seu E-commerce</p>
    <ul class="socials">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-youtube"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
    </ul>
    <div class="footer-bottom">
        <p>copyright &copy;2021 SySales.</p>
    </div>


{% endblock %}

app/templates/snippets/nav-bar-sem-pesquisa.html
{% load static %}

{% block navbar %}

<link rel="stylesheet" href="{% static 'css/style-nav.css' %}">
<style>
nav .content {
  display: flex;
  position: relative;
  align-items: center;
  justify-content: center;
}

.logo a {
  margin: 0 auto;
}

</style>


<div class="wrapper">

  <nav>
      <div class="content">
      <div class="logo"><a href="{% url 'home' %}">SySales</a></div>
      </div>
  </nav>

</div>


  <script src="{% static 'js/nav-bar.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.js"></script>

{% endblock %}

app/templates/snippets/nav-bar.html
{% load crispy_forms_tags %}
{% load static %}

{% block navbar %}

<link rel="stylesheet" href="{% static 'css/style-nav.css' %}">

<div class="wrapper">

  <nav>
      <input type="checkbox" id="show-search">
      <input type="checkbox" id="show-menu">
      <label for="show-menu" class="menu-icon"><i class="fas fa-bars"></i></label>
      <div class="content">
      <div class="logo"><a href="{% url 'home' %}">SySales</a></div>
        <ul class="links">
          <li>
            {% if user.is_authenticated %}
            <li>
                <a href="#" class="desktop-link">Olá, {{user.nome_usuario}}!</a>
                <input type="checkbox" id="show-features">
                <label for="show-features">Olá, {{user.nome_usuario}}!</label>
                <ul>
                  <li><a href="{% url 'users:retorna_perfil' %}">Meu perfil</a></li>
                  <li><a href="{% url 'users:cadastrar_endereco' %}">Cadastre um Endereço</a></li>
                  {% if user.is_superuser %}
                        <li><a href="/admin">Cadastrar produtos</a></li>
                    {% endif %}
                  <li><a href="{% url 'logout' %}">Sair</a></li>
                </ul>
              </li>
            {% else %}
              <li>
                  <a href="{% url 'login' %}">Faça Login</a>
              </li>
              <li>
                  <a href="{% url 'users:cadastrar' %}">Cadastre-se</a>    
              </li>
            {% endif %}
            <li><a href="https://github.com/FarinhaProgrammer/G2-E-Commerce#readme">Quem somos</a></li>
            <li><a href="{% url 'carrinho:retrieve' %}">Carrinho<!--<i class="fas fa-shopping-cart fa-lg"></i>--></a></li>
          <li>
            <a href="#" class="desktop-link">Destaques</a>
            <input type="checkbox" id="show-features1">
            <label for="show-features1">Destaques</label>
            <ul>
              <li><a href="{% url 'produtos:maisVendidos' %}">Mais Vendidos</a></li>
              <li><a href="{% url 'produtos:maisVistos' %}">Mais Visitados</a></li>
              <li><a href="{% url 'produtos:lancamentos' %}">Lançamentos</a></li>
            </ul>
          </li>
        </ul>
      </div>
      <label for="show-search" class="search-icon"><i class="fas fa-search"></i></label>
      <form method="POST" class="search-box">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="go-icon"><i class="fas fa-long-arrow-alt-right"></i></button>
      </form>
  </nav>

</div>  


  <script src="{% static 'js/nav-bar.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.js"></script>

{% endblock %}