app/Ecommerce/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls.static import static
from . import settings
from .views import home
import produtos.urls
import categorias.urls
import accounts.urls
import carrinho.urls
import pedidos.urls

urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('allauth.socialaccount.providers.google.urls')),
    path('accounts/', include('allauth.socialaccount.providers.twitter.urls')),
    path('accounts/', include('allauth.urls'), name='socialaccount_signup'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('users/', include(accounts.urls, namespace='users')),
    path('produtos/', include(produtos.urls)),
    path('categorias/', include(categorias.urls)),
    path('carrinho/', include(carrinho.urls)),
    path('pedidos/', include(pedidos.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/urls.py
from django.urls import path
from accounts.views import addEndereco, cadastra_user, retorna_account, remover_endereco, retorna_perfil

app_name = 'account'

"""
Urls do app account.
"""

urlpatterns = [
    path('<int:pk>/', retorna_account, name='retrieve'),
    path('cadastrar/', cadastra_user, name='cadastrar'),
    path('cadastrar_endereco/', addEndereco, name='cadastrar_endereco'),
    path('remover_endereco/<int:pk>/', remover_endereco, name='remover_endereco'),
    path('perfil/', retorna_perfil, name='retorna_perfil')
]

app/carrinho/urls.py
from django.urls import path
from carrinho.views import retorna_carrinho, adicionar, remover

app_name = 'carrinho'

"""
URLs do app carrinho.
"""

urlpatterns = [
    path('', retorna_carrinho, name='retrieve'),
    path('adicionar/<int:pk>/', adicionar, name='adicionar'),
    path('remover/<int:pk>/', remover, name='remover')
]

app/pedidos/urls.py
from django.urls import path
from pedidos.views import identificacao, pagamento, session_cart_to_account_cart, inicia_pedido, continua_pedido, finaliza_pedido, confirmacao_pedido
from accounts.views import retorna_enderecos

app_name = 'pedidos'

"""
Urls do app pedidos.
"""

urlpatterns = [
    path('identificacao/', identificacao, name='identificacao'),
    path('endereco/', retorna_enderecos, name='endereco'),
    path('pagamento/', pagamento, name='pagamento'),
    path('session-to-account/', session_cart_to_account_cart, name='session-to-account'),
    path('inicia-pedido/', inicia_pedido, name='inicia-pedido'),
    path('continua-pedido/', continua_pedido, name='continua-pedido'),
    path('finaliza-pedido/<int:fm>/', finaliza_pedido, name='finaliza-pedido'),
    path('confirmacao/', confirmacao_pedido, name='confirmacao')
]

app/pedidos/models.py
from django.db import models
from accounts.models import Endereco, MyUser
from produtos.models import Produto

class Pedido(models.Model):

    CHOICES = (
        ('P', 'Pix',),
        ('B', 'Boleto',),
        ('C', 'Crédito',),
    )

    usuario                 = models.ForeignKey(MyUser, on_delete=models.CASCADE, related_name='pedidos')
    produtos                = models.ManyToManyField(Produto, related_name='pedidos')
    valor                   = models.DecimalField(decimal_places=2, max_digits=15)
    forma_pagamento         = models.CharField(max_length=1, choices=CHOICES)
    endereco                = models.ForeignKey(Endereco, on_delete=models.SET_DEFAULT, default='Excluído', related_name='pedidos')
    quantidade_produtos     = models.JSONField()
    frete                   = models.DecimalField(decimal_places=2, max_digits=9)
    foi_pago                = models.BooleanField(default=False)

app/pedidos/forms.py
from django import forms
from pedidos.models import Pedido

class PedidoForm(forms.ModelForm):

    class Meta:
        model = Pedido
        fields = ('forma_pagamento', 'endereco')

app/pedidos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from json import loads
from produtos.models import Produto
from accounts.models import Endereco
from pedidos.models import Pedido

def identificacao(request):
    """
    Esta função confere se o carrinho está vazio ou não, tanto o da sessão quanto o carrinho quando está logado,
    e então retorna o template pro usuário se identificar. Se o carrinho estiver vazio, retornará um template de erro.
    """
    if request.user.is_authenticated:
        if len(request.user.carrinho.produtos.all()) != 0:
            return render(request, 'pedidos/identificacao.html')
        else:
            return render(request, 'erro.html', {'message': 'Seu carrinho está vazio.'})
    else:
        if request.session.get('cart_products', False):
            if request.session['cart_products']:
                return render(request, 'pedidos/identificacao.html')
            else:
                return render(request, 'erro.html', {'message': 'Seu carrinho está vazio.'})
        else:
            return render(request, 'erro.html', {'message': 'Seu carrinho está vazio.'})


@login_required(login_url='/login/')
def pagamento(request):
    """
    Esta função retorna pega o total, o frete, o endereço e a quantidade de produtos, e então retorna o template para selecionar o modo de pagamento.
    """
    endereco = get_object_or_404(Endereco, pk=request.session['pedido'].get('endereco'))
    dados = request.user.carrinho.produtos.all()
    total = request.session['pedido'].get('total')
    frete = request.session['pedido'].get('frete')
    total_final = total + frete
    total_itens = 0
    for i in request.session['pedido'].get('qtd'):
        total_itens += int(i.get('qtd'))
    return render(request, 'pedidos/pagamentos.html', {'endereco': endereco, 'dados': dados, 'total_itens': total_itens, 'total': total, 'frete': frete, 'total_final': total_final})


def session_cart_to_account_cart(request):
    """
    Esta função pega todos os itens presentes no carrinho da sessão e passa para o carrinho do usuário logado.
    Caso o usuário não esteja logado, é retornado um template de erro.
    """
    if request.GET.get('authenticated', False):
        if request.user.is_authenticated:
            products = request.session['cart_products']
            products = [loads(v) for k, v in products.items()]
            products = [p[0] for p in products]
            products = [get_object_or_404(Produto, pk=i['pk']) for i in products]
            [request.user.carrinho.produtos.add(i) for i in products]
            del request.session['cart_products']
        else:
            return render(request, 'erro.html', {'message': 'Usuário não autenticado.'})
    return redirect("/pedidos/identificacao/")


@login_required(login_url='/login/')
def finaliza_pedido(request, fm):
    """
    Esta função pega o numero enviado, confere qual a forma de pagamento, se não existe retorna um template de erro,
    e se existe, pega todas as informações, cria um modelo de pedido e salva. Ao salvar, o carrinho e a sessão são limpos.
    """
    print("finaliza pedido")
    fms = {1:'B', 2:'P', 3:'C'}
    if fms.get(fm, False):
        endereco = get_object_or_404(Endereco, id=request.session['pedido'].get('endereco'))
        pedido = Pedido.objects.create(usuario=request.user, valor=request.session['pedido'].get('total'), forma_pagamento=fms.get(fm), endereco=endereco, quantidade_produtos=request.session['pedido'].get('qtd'), frete=request.session['pedido'].get('frete'))
        [pedido.produtos.add(i.id) for i in request.user.carrinho.produtos.all()]
        pedido.save()
        request.user.carrinho.produtos.clear()
        del request.session['pedido']
    else:
        return render(request, 'erro.html', {'message': 'Pagina não encontrada.'})
    return redirect("/")


def inicia_pedido(request):
    """
    Cria uma nova chave no dicionário da sessão, então preenche com outro dicionário, contendo informações sobre os produtos,
    como frete, quantidade, preço unitário, preço total e preço total de todos os produtos.
    A cada nova alteração no template, o ajax dispara um POST para esta função.
    """
    request.session['pedido'] = {}
    dados = []
    dicio = {}
    for k, v in request.POST.items():
        if 'id' in k:
            dicio['id'] = v
        elif 'qtd' in k:
            dicio['qtd'] = v
        elif 'unit' in k:
            dicio['unit'] = v
        elif 'total' in k:
            dicio['total'] = v
            dados.append(dicio)
            dicio = {}
        else:
            frete = v
    
    qtd_produtos = [{get_object_or_404(Produto, id=i['id']).nome: i['id'], 'qtd': i['qtd'], 'preco_unitario': i['unit']} for i in dados]
    total = 0
    for i in dados:
        total += float(i['total'])
    request.session['pedido']['qtd'] = qtd_produtos
    request.session['pedido']['total'] = total
    request.session['pedido']['frete'] = float(frete)
    request.session.modified = True
    print(request.session.get('pedido', False))
    return redirect("/carrinho/")


def continua_pedido(request):
    """
    Esta função pega o pedido já existente na sessão e complementa com o id do endereço escolhido.
    """
    endereco = request.GET.get('id')
    request.session['pedido']['endereco'] = endereco
    request.session.modified = True
    return redirect("/pedidos/pagamento/")

def confirmacao_pedido(request, pk):
    pedido = get_object_or_404(Pedido, pk=pk)
    if pedido.foi_pago == True:
        msg = 'Pago'
    else:
        msg = 'Não pago'
    return render(request, 'pedidos/confirmacao.html', {'mensagem': msg})

app/templates/pedidos/confirmacao.html
{% extends 'index.html' %}

{% load static %}

{% block title %}Confirmação de pagamento{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/style-confirmacao.css' %}">

{% if mensagem == 'Pago' %}

<section class="section-confirm">

    <p>Seu pedido foi pago e está a caminho!</p> 
    <p>Obrigado por comprar conosco!</p>

</section>

{% else %}

<section class="section-confirm">

    <p>Seu pagamento ainda não recebido</p> 
    <p>Assim que for detectado, seu pedido será encaminhado!</p>

</section>

{% endif %}

{% endblock %}

app/templates/pedidos/endereco.html
{% extends 'pedidos/index-pedidos.html' %}

{% load static %}
   
{% block content %}

<link rel="stylesheet" href="{% static 'css/checkout.css' %}">

<section>
    <div class="wrapper">
        
        <div class="checkout">
   
            <div class="titulo">
                <span class="fas fa-home"></span>
                <h1>Endereços</h1>
            </div><!--/titulo-->

            <p class="novo-endereco">Meus Endereços</p>

            {% if dados %}

            {% for endereco in dados %}

            <div class="meus-enderecos">

                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td class="dados">
                        <table>
                        <tr>
                            <td align="right"><b>Nome do Endereço:</b></td>
                            <br><td>{{endereco.nome}}</td>
                        </tr>
                        <tr>
                        <tr>
                            <td align="right"><b>Destinatario:</b></td>
                            <td>{{endereco.usuario}}</td>
                        </tr>
                        <tr>
                            <td align="right"><b>Endereço:</b></td>
                            <td>{{endereco.rua}}, {{endereco.numero}}</td>
                        </tr>
                        <tr>
                            <td align="right"><b>Bairro:</b></td>
                            <td>{{endereco.bairro}}</td>
                        </tr>
                        <tr>
                            <td align="right"><b>CEP:</b></td>
                            <td>{{endereco.cep}}</td>
                        </tr>
                        <tr>
                            <td align="right"><b>Cidade:</b></td>
                            <td>{{endereco.cidade}} - {{endereco.estado}} - {{endereco.pais}}</td>
                        </tr>
                        <tr>
                            <td align="right"><b>Referência:</b></td>
                            <td>{{endereco.referencia}}</td>
                        </tr>
                        </table>
                    </td>
                  </tr>
                </table>
                
                <a href="{% url 'users:remover_endereco' pk=endereco.id %}?next=/pedidos/endereco/" class="endereco-btn">Excluir</a>
                <a href="{% url 'pedidos:continua-pedido' %}?id={{endereco.id}}" class="endereco-btn">Selecionar endereço</a>
                  
            </div><!--/meus-enderecos-->
            <br>  

            {% endfor %}

            {% else %}

                <table align="center" width="100%" border="0" cellspacing="0" cellpadding="0">
                
                    <tr>
                        <td align="right"><b>Você não tem nenhum endereço cadastrado.</b></td>
                    </tr>

                </table>

            {% endif %}

            <div class="novo-endereco">

              <h2>Incluir um novo endereço</h2>

               <a href="{% url 'users:cadastrar_endereco' %}?next=/pedidos/endereco/" class="endereco-btn" id="incluir">Incluir Endereço</a>
            
            </div><!--/novo-endereco-->
          
            
            

    </div><!--/checkout-->
        
        
     </div><!--/wrapper-->
</section>

{% endblock %}

app/templates/pedidos/identificacao.html
{% extends 'pedidos/index-pedidos.html' %}

{% load static %}
   
{% block content %}

<link rel="stylesheet" href="{% static 'css/checkout.css' %}">

<style>
    span a {
        color: black;
        text-decoration: none;
    }

</style>

<section>
    <div class="wrapper">
    
        <div class="checkout">
   
            <div class="titulo">
                <span class="fa fa-user"></span>
                <h1>Identificação</h1>
            </div><!--/titulo-->
            
            {% if user.is_authenticated %}

                <div class="entrar">
                    <span>Você já está autenticado como: {{request.user.nome_usuario}}.</span>
                    <br><br>
                    <div class="bt-concluir-compra"><a href="{% url 'pedidos:endereco' %}">Continuar > </a></div>

                    <div class="alterar-pedido">
                        <a href="{% url 'carrinho:retrieve' %}"><< alterar pedido</a>
                    </div><!--/alterar-pedido-->
                    
                </div><!--/entrar-->

                <div class="cadastrar">
                    <span>Deseja se autenticar como outra pessoa?</span>
                    <br><br><br>
                    <div class="bt-continuar-comprando"><a href="{% url 'login' %}?next=/pedidos/identificacao/"> Faça login ></a></div>
                </div><!--/cadastrar-->

            {% else %}

            <div class="entrar">
                <span>Já tenho cadastro</span>
                <span><a href="{% url 'login' %}">Clique aqui para fazer login.</a></span>
                <div class="bt-concluir-compra"><a href="{% url 'login' %}?next=/pedidos/session-to-account/?authenticated=True">Continuar > </a></div>

                <div class="alterar-pedido">
                    <a href="{% url 'carrinho:retrieve' %}"><< alterar pedido</a>
                </div><!--/alterar-pedido-->
                
            </div><!--/entrar-->

            <div class="cadastrar">
                <span>Ainda não tenho cadastro</span>
                <br><br><br>
                <div class="bt-continuar-comprando"><a href="{% url 'users:cadastrar' %}?next=/pedidos/session-to-account/?authenticated=True"> Criar cadastro ></a></div>
            </div><!--/cadastrar-->
             
            {% endif %}

        </div><!--/checkout-->
        
        
     </div><!--/wrapper-->
</section>

{% endblock %}

app/templates/pedidos/index-pedidos.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}SySales{% endblock %}</title>
    <link href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glider-js@1/glider.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
</head>
<body>

    <!-- BARRA DE NAVEGAÇÃO -->

    <header>
        
      {% include 'snippets/nav-bar-sem-pesquisa.html' %}

    </header>  

    <!-- BLOCO DE CONTEÚDO -->

    <main>    

        {% block content %}

        {% endblock %}

    </main>

    <!-- FOOTER -->

    <!-- <footer class="footer-content">

        {% include 'snippets/footer.html' %}

    </footer> -->

    <script src="https://getbootstrap.com/docs/5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/76b3a9fc76.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/cep.js' %}"></script>
    <script src="{% static 'js/ajax.js' %}"></script>
</body>
</html>

app/templates/pedidos/pagamentos.html
{% extends 'pedidos/index-pedidos.html' %}

{% load static %}
   
{% block title %}Pagamento{% endblock %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/checkout.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<section>
    <div class="wrapper">
    
        <div class="checkout">
   
            <div class="titulo">
                <span class="fa fa-credit-card"></span>
                <h1>Pagamento</h1>
            </div><!--/titulo-->
            

            <div class="seu-pedido">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td colspan="2" class="header" >Seu pedido <a id="revisar-pedido" href="{% url 'carrinho:retrieve' %}">Revisar pedido</a></td>
                  </tr>
                  <tr>
                    <td class="dados">Total em Produtos ({{total_itens}} itens)</td>
                    <td class="dados">R$ {{total}}</td>
                  </tr>
                  <tr>
                    <td class="dados">Frete</td>
                    <td class="dados">R$ {{frete}}</td>
                  </tr>
                  <tr>
                    <td class="total">Total</td>
                    <td class="total">R$ {{total_final}}</td>
                  </tr>
                </table>
            </div><!--/seu-pedido-->
            
             <div class="endereco-entrega">
                 <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td colspan="2" class="header" >Endereço de Entrega <a href="{% url 'pedidos:endereco' %}">Selecionar outro endereço</a></td>
                  </tr>
                  <tr>
                    <td class="dados"><strong>Meu Endereço</strong></td>
                  </tr>
                  <tr>
                    <td class="dados">
                      <table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td class="dados">
                              <table>
                              <tr>
                                  <td align="right"><b>Nome do Endereço:</b></td>
                                  <br><td>{{endereco.nome}}</td>
                              </tr>
                              <tr>
                              <tr>
                                  <td align="right"><b>Destinatario:</b></td>
                                  <td>{{endereco.usuario}}</td>
                              </tr>
                              <tr>
                                  <td align="right"><b>Endereço:</b></td>
                                  <td>{{endereco.rua}}, {{endereco.numero}}</td>
                              </tr>
                              <tr>
                                  <td align="right"><b>Bairro:</b></td>
                                  <td>{{endereco.bairro}}</td>
                              </tr>
                              <tr>
                                  <td align="right"><b>CEP:</b></td>
                                  <td>{{endereco.cep}}</td>
                              </tr>
                              <tr>
                                  <td align="right"><b>Cidade:</b></td>
                                  <td>{{endereco.cidade}} - {{endereco.estado}} - {{endereco.pais}}</td>
                              </tr>
                              <tr>
                                  <td align="right"><b>Referência:</b></td>
                                  <td>{{endereco.referencia}}</td>
                              </tr>
                              </table>
                          </td>
                        </tr>
                      </table>
                    </td>
                    </tr>
                </table>
            </div><!--/endereco-entrega-->
            
            <div class="titulo">
                <p>Escolha a Forma de Pagamento</p>
            </div><!--/titulo-->
            
          <div class="forma-de-pagamento" id="B">
                <div class="tipo">
                    <p><span>Boleto</span><br>Pagamento com boleto bancário</p>
                    <div class="bt-selecionar"><a href="{% url 'pedidos:finaliza-pedido' fm=1 %}">Selecionar</a></div>
                </div><!--/tipo--> 
                <br><br> 
          </div><!--/forma-de-pagamento-->         
    </div><!--/checkout-->        
    </div><!--/wrapper-->
</section>

{% endblock %}