app/Ecommerce/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from django.conf.urls.static import static
from . import settings
from .views import home
import produtos.urls
import categorias.urls
import accounts.urls
import carrinho.urls
import pedidos.urls

urlpatterns = [
    path('', home, name='home'),
    path('accounts/', include('allauth.socialaccount.providers.google.urls')),
    path('accounts/', include('allauth.socialaccount.providers.twitter.urls')),
    path('accounts/', include('allauth.urls'), name='socialaccount_signup'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('users/', include(accounts.urls, namespace='users')),
    path('produtos/', include(produtos.urls)),
    path('categorias/', include(categorias.urls)),
    path('carrinho/', include(carrinho.urls)),
    path('pedidos/', include(pedidos.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/carrinho/urls.py
from django.urls import path
from carrinho.views import retorna_carrinho, adicionar, remover

app_name = 'carrinho'

"""
URLs do app carrinho.
"""

urlpatterns = [
    path('', retorna_carrinho, name='retrieve'),
    path('adicionar/<int:pk>/', adicionar, name='adicionar'),
    path('remover/<int:pk>/', remover, name='remover')
]

app/pedidos/urls.py
from django.urls import path
from pedidos.views import identificacao, pagamento, session_cart_to_account_cart, inicia_pedido, continua_pedido, finaliza_pedido, confirmacao_pedido
from accounts.views import retorna_enderecos

app_name = 'pedidos'

"""
Urls do app pedidos.
"""

urlpatterns = [
    path('identificacao/', identificacao, name='identificacao'),
    path('endereco/', retorna_enderecos, name='endereco'),
    path('pagamento/', pagamento, name='pagamento'),
    path('session-to-account/', session_cart_to_account_cart, name='session-to-account'),
    path('inicia-pedido/', inicia_pedido, name='inicia-pedido'),
    path('continua-pedido/', continua_pedido, name='continua-pedido'),
    path('finaliza-pedido/<int:fm>/', finaliza_pedido, name='finaliza-pedido'),
    path('confirmacao/', confirmacao_pedido, name='confirmacao')
]

app/produtos/urls.py
from produtos.views import retorna_produtos, retorna_produtos_mais_recentes, retorna_produtos_mais_vendidos, retorna_produtos_mais_visualizados, detalhes_produto
from django.urls import path

app_name = 'produtos'

"""
URLs do app produtos.
"""

urlpatterns = [
    path('<int:pk>/', detalhes_produto, name='detalhes_produto'),
    path('list/', retorna_produtos, name='list'),
    path('maisVendidos/', retorna_produtos_mais_vendidos, name='maisVendidos'),
    path('maisVistos/', retorna_produtos_mais_visualizados, name='maisVistos'),
    path('lancamentos/', retorna_produtos_mais_recentes, name='lancamentos'),
]

app/carrinho/models.py
from django.db import models
from produtos.models import Produto

class Carrinho(models.Model):
    """
    Modelo de carrinho de compras com seus respectivos campos.

    Um usuário pode ter apenas um carrinho, e um carrinho pode ter apenas um usuário.
    """
    usuario                 = models.OneToOneField("accounts.MyUser", on_delete=models.CASCADE, related_name='carrinho')
    produtos                = models.ManyToManyField(Produto, related_name='carrinho')
    

app/carrinho/views.py
from django.shortcuts import render, get_object_or_404
from produtos.models import Produto
from carrinho.models import Carrinho
from produtos.views import produto_queryset_parser
from django.core.serializers import serialize
from json import loads
from produtos.forms import SearchForm
from produtos.views import search

def retorna_carrinho(request):
    """
    Esta função retorna o carrinho em formato json, e confere se o carrinho é de sessão,
    ou se é de um usuário logado.
    """
    if request.method == 'POST':
        return search(request)
    else:
        form = SearchForm()
    if request.user.is_authenticated:
        dados = get_object_or_404(Carrinho, pk=request.user.carrinho.pk)
        if len(dados.produtos.all()) == 0:
            return render(request, 'carrinho/carrinho.html', {'no_match': True})
        produtos = [get_object_or_404(Produto, id=i.id) for i in dados.produtos.all()]
        # total do carrinho
        total_itens = len(produtos)
        total = [i.preco for i in produtos]
        total = sum(total)
        
        return render(request, 'carrinho/carrinho.html', {'dados': produtos, 'total_itens': total_itens, 'total': total, 'no_match': False})
    else:
        if request.session.get('cart_products', False):
            products = request.session['cart_products']
            if not products:
                return render('carrinho/carrinho.html', {'no_match': True})
            products = [loads(v) for k, v in products.items()]
            products = [p[0] for p in products]
            products = produto_queryset_parser(products, to_session_cart=True)
            total_itens = len(products)
            total = [float(p['preco']) for p in products]
            total = sum(total)
        else:
            return render(request, 'carrinho/carrinho.html', {'no_match': True})

        return render(request, 'carrinho/carrinho.html', {'dados': products, 'total_itens': total_itens, 'total': total, 'no_match': False, 'form': form})    

def adicionar(request, pk):
    """
    Esta função adiciona um item ao carrinho, se o usuário estiver logado, e se não estiver,
    adiciona um item ao carrinho da sessão.
    """
    produto = get_object_or_404(Produto, pk=pk)
    if request.user.is_authenticated:
        carrinho = get_object_or_404(Carrinho, id=request.user.carrinho.id)
        carrinho.produtos.add(produto)
    else:

        if request.session.get('cart_products', False):
            request.session['cart_products'][produto.pk] = serialize('json', [produto])
        else:
            request.session['cart_products'] = {}
            request.session['cart_products'][produto.pk] = serialize('json', [produto])

        request.session.modified = True

    return render(request, 'produtos/detalhes_produto.html', {'produto': produto, 'in_cart': True})


def remover(request, pk):
    """
    Esta função remove um item do carrinho, se o usuário estiver logado, e se não estiver,
    remove um item do carrinho da sessão.
    """
    produto = get_object_or_404(Produto, pk=pk)

    if request.user.is_authenticated:
        carrinho = get_object_or_404(Carrinho, id=request.user.carrinho.id)
        carrinho.produtos.remove(produto)
    else:
        if request.session.get('cart_products', False):
            if request.session['cart_products'].get(str(produto.pk), False):
                request.session['cart_products'].pop(str(produto.pk))
            else:
                return render(request, 'erro.html', {'message': 'Este produto não está no seu carrinho'})
        else:
            request.session['cart_products'] = {}
            return render(request, 'erro.html', {'message': 'Este produto não está no seu carrinho'})

    request.session.modified = True

    if 'carrinho' in request.path:
        return retorna_carrinho(request)

    return render(request, 'produtos/detalhes_produto.html', {'produto': produto, 'in_cart': False})

app/templates/carrinho/carrinho.html
{% extends 'pedidos/index-pedidos.html' %}

{% load static %}

{% block title %}Carrinho{% endblock %}

{% block content %}

<link href="{% static 'css/checkout.css' %}" rel="stylesheet" type="text/css"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/ajax-carrinho.js' %}"></script>

<section id="carrinho">
    <div class="wrapper">
    
        <div class="checkout">

            <div class="titulo">
                <span class="fa fa-shopping-cart"></span>
                <h1>Meu Carrinho</h1>
            </div>
            
            {% if no_match%}

            <div class="carrinho">
              <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="55%" class="header">Produto(s) no Meu Carrinho</td>
                  <td width="15%" class="header">Quantidade</td>
                  <td width="15%" class="header">Valor Unitário</td>
                  <td width="15%" class="header">Valor Total</td>
                </tr>
                <tr >
                  <td class="dados"> 
                      <div id="" class="carrinho-descricao-produto">
                         <a><strong><p>Seu carrinho está vazio...</p></strong></a>
                      </div><!--/carrinho-descricao-produto-->
                  </td>
                  <td class="dados" align="center">
                      <div class="quantidade">
                      </div><!--/quantidade-->
                      <div class="bt-excluir">
                      </div><!--/excluir-->
                  </td>
                  <td class="dados unit" align="center" name="valor unitário"></td>
                  <td class="dados mult" align="center" name="valor total"></td>
                </tr>
                <tr>
                    <td colspan="3" class="frete"> 
                      <table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                          <td width="7%" align="center"><span class="fa fa-truck"></span></td>
                          <td width="30%" align="left">Consulte o frete para seu CEP</td>
                          <td width="1%" align="left"><input name="" id="cep" type="number" min="1000000" max="99999999" value="01000000" class="p" ></td>
                          <td width="1%"><div class="bt-ok"><a href="#">OK</a></div></td>
                          <td width="10%" align="right">FRETE</td>
                        </tr>
                      </table>
                  </td>
                  <td class="dados frete-result" align="center"></td>
                </tr>
                <tr id="total">
                  <td colspan="3" align="right" class="subtotal">TOTAL</td>
                  <td class="dados total-carrinho" align="center">{{total}}</td>
                </tr>
               </table>
          
          </div><!--/carrinho-->

            {% else %}
            
            <div class="carrinho">
                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td width="50%" class="header">Produto(s)</td>
                    <td width="15%" class="header">Quantidade</td>
                    <td width="20%" class="header">Valor Unidade</td>
                    <td width="15%" class="header">Valor Total</td>
                  </tr>

                  {% for produto in dados %}

                  <tr >
                    <td class="dados">
                        <div class="carrinho-imagem-produto">
                            <!-- <img src="{{produto.imagem.url}}" max-width="210" max-height="210"> -->
                        </div><!--/carrinho-imagem-produto-->
                        
                        <div id="{{produto.id}}" class="carrinho-descricao-produto">
                           <a><strong>{{produto.nome}}</strong></a>
                        </div><!--/carrinho-descricao-produto-->
                    </td>
                    <td class="dados" align="center">
                        <div class="quantidade">
                            <input value="1" type="number" class="pp" max="50" min="1">
                            <!--/controle-de-unidades-->
                        </div><!--/quantidade-->
                        <div class="bt-excluir">
                            <button class="ajax-class" value="{% url 'carrinho:remover' pk=produto.id %}"><i class="far fa-trash-alt"></i></button>
                        </div><!--/excluir-->
                    </td>
                    <td class="dados unit" align="center" name="valor unitário">{{produto.preco}}</td>
                    <td class="dados mult" align="center" name="valor total">{{produto.preco}}</td>
                  </tr>
                  
                  {% endfor %}

                  <tr>
                      <td colspan="3" class="frete"> 
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                          <tr>
                            <td width="7%" align="center"> 
                              <!-- <span class="fa fa-truck"></span> -->
                              <span></span>
                            </td>
                            <td width="30%" align="left">Consulte o frete</td>
                            <td width="1%" align="left"><input name="" id="cep" type="number" min="1000000" max="99999999" value="01000000" class="p" ></td>
                            <td width="1%"><div class="bt-ok"><a href="#">OK</a></div></td>
                            <td width="10%" align="right">FRETE</td>
                          </tr>
                        </table>
                    </td>
                    <td class="dados frete-result" align="center"></td>
                  </tr>
                  <tr id="total">
                    <td colspan="3" align="right" class="subtotal">TOTAL</td>
                    <td class="dados total-carrinho" align="center">{{total}}</td>
                  </tr>
                 </table>
            
            </div><!--/carrinho-->

            {% endif %}
            
            <div class="bt-continuar-comprando"><a href="{% url 'produtos:lancamentos' %}"> < continuar comprando</a></div>
            <div class="bt-concluir-compra"><a href="{% url 'pedidos:identificacao' %}">concluir compra > </a></div>
    
        </div><!--/checkout-->       
     </div><!--/wrapper-->
</section>

{% endblock %}